In [14]:
import pandas as pd
import numpy as np

In [26]:
df = pd.read_csv('dataset_ori.csv')
del df['Unnamed: 0']
df

,date,number,name,div,a,b,c,d,e,f,...,k,l,m,n,o,p,q,r,s,t
0,2008-01-01,150,서울역(150),승차,379,287,371,876,965,1389,...,2520,3078,3495,3055,2952,2726,3307,2584,1059,264
1,2008-01-01,150,서울역(150),하차,145,707,689,1037,1170,1376,...,1955,2304,2203,2128,1747,1593,1078,744,406,558
2,2008-01-01,151,시청(151),승차,131,131,101,152,191,202,...,892,900,1154,1706,1444,1267,928,531,233,974
3,2008-01-01,151,시청(151),하차,35,158,203,393,375,460,...,1157,1153,1303,1190,830,454,284,141,107,185
4,2008-01-01,152,종각(152),승차,1287,867,400,330,345,338,...,1867,2269,2777,2834,2646,2784,2920,2290,802,1559
5,2008-01-01,152,종각(152),하차,74,147,261,473,597,698,...,2161,2298,2360,1997,1217,799,461,271,134,210
6,2008-01-01,153,종로3가(153),승차,484,290,192,218,281,429,...,1652,2000,1768,1745,1556,1598,1487,1318,455,1499
7,2008-01-01,153,종로3가(153),하차,28,80,116,238,390,609,...,1991,1896,1543,1160,926,431,324,190,127,384
8,2008-01-01,154,종로5가(154),승차,89,77,86,115,122,192,...,553,647,596,421,335,237,154,134,47,140
9,2008-01-01,154,종로5가(154),하차,14,76,93,123,137,193,...,445,399,393,272,190,167,138,125,104,42
10,2008-01-01,155,동대문(155),승차,190,149,152,253,365,390,...,900,891,867,764,587,489,386,287,155,139
11,2008-01-01,155,동대문(155),하차,23,111,120,150,299,331,...,1061,987,891,757,578,451,500,426,231,221
12,2008-01-01,156,신설동(156),승차,65,107,113,183,244,248,...,448,407,432,389,290,250,235,143,49,19
13,2008-01-01,156,신설동(156),하차,15,98,81,112,166,202,...,324,347,394,397,321,297,332,279,186,89
14,2008-01-01,157,제기동(157),승차,156,129,115,193,279,385,...,860,921,759,557,382,280,193,124,47,62
15,2008-01-01,157,제기동(157),하차,16,84,84,175,256,384,...,747,561,434,373,333,268,247,236,148,85
16,2008-01-01,158,청량리(지하)(158),승차,230,292,351,588,779,1076,...,2097,2152,2141,2109,1951,1534,1374,1001,316,60
17,2008-01-01,158,청량리(지하)(158),하차,56,428,510,522,872,1059,...,1848,1698,1777,1410,1254,1147,1068,900,546,403
18,2008-01-01,159,동묘앞(159),승차,27,26,22,41,63,109,...,428,441,367,194,112,92,73,70,26,10
19,2008-01-01,159,동묘앞(159),하차,3,45,54,84,96,132,...,371,309,184,158,101,128,106,117,86,61
20,2008-01-01,201,시청(201),승차,55,93,67,126,139,97,...,471,577,734,956,782,695,513,287,135,570
21,2008-01-01,201,시청(201),하차,29,107,131,196,262,237,...,794,757,795,799,456,385,200,113,70,148
22,2008-01-01,202,을지로입구(202),승차,163,96,106,129,245,245,...,1150,1519,1720,1994,1820,1842,1816,1216,329,1188
23,2008-01-01,202,을지로입구(202),하차,31,176,278,565,547,813,...,1712,1621,1448,1080,521,335,206,112,48,219
24,2008-01-01,203,을지로3가(203),승차,23,55,36,69,79,384,...,238,218,299,252,250,194,148,117,59,107
25,2008-01-01,203,을지로3가(203),하차,12,81,79,251,428,470,...,240,203,204,189,105,87,60,48,30,34
26,2008-01-01,204,을지로4가(204),승차,11,34,23,56,81,62,...,147,159,185,133,100,76,84,50,9,22
27,2008-01-01,204,을지로4가(204),하차,8,45,34,85,60,77,...,137,95,86,78,75,48,52,37,24,32
28,2008-01-01,205,동대문운동장(205),승차,174,131,109,171,210,178,...,875,1054,1087,1040,844,708,572,407,247,151
29,2008-01-01,205,동대문운동장(205),하차,24,100,102,168,242,377,...,1010,973,895,729,636,448,380,298,232,151
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1922006,2017-09-30,2813,강동구청,승차,120,239,397,561,601,519,...,547,596,603,499,299,195,154,116,56,14
1922007,2017-09-30,2813,강동구청,하차,27,149,211,311,321,297,...,469,514,589,555,497,383,494,516,288,148
1922008,2017-09-30,2814,몽촌토성,승차,67,90,165,273,254,287,...,657,781,986,772,453,237,223,200,80,0
1922009,2017-09-30,2814,몽촌토성,하차,32,163,189,256,367,427,...,618,522,458,354,205,216,229,264,111,17
1922010,2017-09-30,2815,잠실(8),승차,73,92,131,179,238,269,...,942,1177,1160,1311,1182,1150,1142,905,344,1
1922011,2017-09-30,2815,잠실(8),하차,27,195,343,785,954,902,...,1319,1505,1104,1023,562,397,300,213,129,44
1922012,2017-09-30,2816,석촌,승차,146,150,290,421,492,410,...,462,557,467,412,286,232,257,149,87,1
1922013,2017-09-30,2816,석촌,하차,25,168,189,360,383,379,...,412,465,520,462,382,310,336,316,230,25
1922014,2017-09-30,2817,송파,승차,71,114,145,265,280,209,...,407,374,357,274,162,151,96,87,45,0
1922015,2017-09-30,2817,송파,하차,65,388,141,224,231,177,...,271,238,259,248,229,139,196,151,114,12
1922016,2017-09-30,2818,가락시장(8),승차,84,129,190,279,366,449,...,479,474,446,399,322,273,295,252,160,1
1922017,2017-09-30,2818,가락시장(8),하차,97,228,255,483,513,445,...,463,470,541,460,379,239,258,193,165,152
1922018,2017-09-30,2819,문정,승차,52,134,226,331,493,346,...,540,697,788,522,249,218,208,233,85,1
1922019,2017-09-30,2819,문정,하차,74,637,433,397,420,340,...,286,339,361,438,412,243,286,302,168,0
1922020,2017-09-30,2820,장지,승차,147,326,422,761,813,704,...,976,1131,1177,1236,909,671,675,828,175,0
1922021,2017-09-30,2820,장지,하차,46,239,384,772,866,635,...,854,1028,912,1116,730,548,563,781,501,1
1922022,2017-09-30,2821,복정(8),승차,108,211,338,583,570,505,...,552,710,747,498,408,237,217,148,74,1
1922023,2017-09-30,2821,복정(8),하차,86,422,290,298,300,256,...,341,361,423,439,427,335,418,461,331,83
1922024,2017-09-30,2822,산성,승차,193,219,337,478,478,326,...,384,407,366,246,200,120,82,53,37,1
1922025,2017-09-30,2822,산성,하차,24,80,95,183,304,288,...,276,361,382,417,348,305,358,438,238,53
1922026,2017-09-30,2823,남한산성입구,승차,309,511,792,1066,1111,838,...,727,728,696,504,299,187,138,115,55,2
1922027,2017-09-30,2823,남한산성입구,하차,35,160,225,310,332,428,...,491,569,713,783,712,687,720,957,646,118
1922028,2017-09-30,2824,단대오거리,승차,284,432,597,886,765,680,...,694,654,640,515,344,215,186,155,74,3
1922029,2017-09-30,2824,단대오거리,하차,55,128,187,274,288,278,...,469,556,611,803,727,580,671,801,606,97
1922030,2017-09-30,2825,신흥,승차,109,190,220,350,329,224,...,354,439,365,298,217,158,157,102,39,0
1922031,2017-09-30,2825,신흥,하차,24,69,72,150,166,170,...,401,349,456,401,374,269,322,265,203,40
1922032,2017-09-30,2826,수진,승차,110,137,248,393,333,268,...,312,358,350,290,173,133,91,73,38,1
1922033,2017-09-30,2826,수진,하차,20,111,59,133,166,186,...,278,280,290,315,277,190,266,212,184,38
1922034,2017-09-30,2827,모란(8),승차,74,91,106,185,197,210,...,293,278,330,260,189,119,123,113,55,0
1922035,2017-09-30,2827,모란(8),하차,16,90,95,143,175,177,...,232,257,224,305,182,155,160,151,112,19

In [7]:
# df2 = pd.melt(df, id_vars=[" 날짜 ", " 역번호 ", " 역명 ", " 구분 "], value_name="t")
# df2 = pd.melt(df, id_vars=["location", "name"], var_name="Date", value_name="Value")
# df2 = pd.melt(df,id_vars=["date", "number", "name", "div","a","b",'c','d','e','f','g','h','i','j','k','l','m','o','p','q','r'], value_name='t')
df2 = pd.melt(df,id_vars=["date", "number", "name", "div","a","b",'c','d','e','f','g','h','i','j','k','l','m','o','p','q','r'], value_name='t')
df2

,date,number,name,div,a,b,c,d,e,f,...,j,k,l,m,o,p,q,r,variable,t
0,2008-01-01,150,서울역(150),승차,379,287,371,876,965,1389,...,2885,2520,3078,3495,2952,2726,3307,2584,n,3055
1,2008-01-01,150,서울역(150),하차,145,707,689,1037,1170,1376,...,2077,1955,2304,2203,1747,1593,1078,744,n,2128
2,2008-01-01,151,시청(151),승차,131,131,101,152,191,202,...,678,892,900,1154,1444,1267,928,531,n,1706
3,2008-01-01,151,시청(151),하차,35,158,203,393,375,460,...,1148,1157,1153,1303,830,454,284,141,n,1190
4,2008-01-01,152,종각(152),승차,1287,867,400,330,345,338,...,1475,1867,2269,2777,2646,2784,2920,2290,n,2834
5,2008-01-01,152,종각(152),하차,74,147,261,473,597,698,...,2089,2161,2298,2360,1217,799,461,271,n,1997
6,2008-01-01,153,종로3가(153),승차,484,290,192,218,281,429,...,1449,1652,2000,1768,1556,1598,1487,1318,n,1745
7,2008-01-01,153,종로3가(153),하차,28,80,116,238,390,609,...,2387,1991,1896,1543,926,431,324,190,n,1160
8,2008-01-01,154,종로5가(154),승차,89,77,86,115,122,192,...,452,553,647,596,335,237,154,134,n,421
9,2008-01-01,154,종로5가(154),하차,14,76,93,123,137,193,...,551,445,399,393,190,167,138,125,n,272
10,2008-01-01,155,동대문(155),승차,190,149,152,253,365,390,...,727,900,891,867,587,489,386,287,n,764
11,2008-01-01,155,동대문(155),하차,23,111,120,150,299,331,...,1054,1061,987,891,578,451,500,426,n,757
12,2008-01-01,156,신설동(156),승차,65,107,113,183,244,248,...,416,448,407,432,290,250,235,143,n,389
13,2008-01-01,156,신설동(156),하차,15,98,81,112,166,202,...,365,324,347,394,321,297,332,279,n,397
14,2008-01-01,157,제기동(157),승차,156,129,115,193,279,385,...,666,860,921,759,382,280,193,124,n,557
15,2008-01-01,157,제기동(157),하차,16,84,84,175,256,384,...,891,747,561,434,333,268,247,236,n,373
16,2008-01-01,158,청량리(지하)(158),승차,230,292,351,588,779,1076,...,2006,2097,2152,2141,1951,1534,1374,1001,n,2109
17,2008-01-01,158,청량리(지하)(158),하차,56,428,510,522,872,1059,...,2078,1848,1698,1777,1254,1147,1068,900,n,1410
18,2008-01-01,159,동묘앞(159),승차,27,26,22,41,63,109,...,299,428,441,367,112,92,73,70,n,194
19,2008-01-01,159,동묘앞(159),하차,3,45,54,84,96,132,...,454,371,309,184,101,128,106,117,n,158
20,2008-01-01,201,시청(201),승차,55,93,67,126,139,97,...,439,471,577,734,782,695,513,287,n,956
21,2008-01-01,201,시청(201),하차,29,107,131,196,262,237,...,756,794,757,795,456,385,200,113,n,799
22,2008-01-01,202,을지로입구(202),승차,163,96,106,129,245,245,...,921,1150,1519,1720,1820,1842,1816,1216,n,1994
23,2008-01-01,202,을지로입구(202),하차,31,176,278,565,547,813,...,1580,1712,1621,1448,521,335,206,112,n,1080
24,2008-01-01,203,을지로3가(203),승차,23,55,36,69,79,384,...,230,238,218,299,250,194,148,117,n,252
25,2008-01-01,203,을지로3가(203),하차,12,81,79,251,428,470,...,236,240,203,204,105,87,60,48,n,189
26,2008-01-01,204,을지로4가(204),승차,11,34,23,56,81,62,...,162,147,159,185,100,76,84,50,n,133
27,2008-01-01,204,을지로4가(204),하차,8,45,34,85,60,77,...,138,137,95,86,75,48,52,37,n,78
28,2008-01-01,205,동대문운동장(205),승차,174,131,109,171,210,178,...,707,875,1054,1087,844,708,572,407,n,1040
29,2008-01-01,205,동대문운동장(205),하차,24,100,102,168,242,377,...,1114,1010,973,895,636,448,380,298,n,729
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5766078,2017-09-30,2813,강동구청,승차,120,239,397,561,601,519,...,556,547,596,603,299,195,154,116,t,14
5766079,2017-09-30,2813,강동구청,하차,27,149,211,311,321,297,...,489,469,514,589,497,383,494,516,t,148
5766080,2017-09-30,2814,몽촌토성,승차,67,90,165,273,254,287,...,457,657,781,986,453,237,223,200,t,0
5766081,2017-09-30,2814,몽촌토성,하차,32,163,189,256,367,427,...,802,618,522,458,205,216,229,264,t,17
5766082,2017-09-30,2815,잠실(8),승차,73,92,131,179,238,269,...,803,942,1177,1160,1182,1150,1142,905,t,1
5766083,2017-09-30,2815,잠실(8),하차,27,195,343,785,954,902,...,1307,1319,1505,1104,562,397,300,213,t,44
5766084,2017-09-30,2816,석촌,승차,146,150,290,421,492,410,...,446,462,557,467,286,232,257,149,t,1
5766085,2017-09-30,2816,석촌,하차,25,168,189,360,383,379,...,457,412,465,520,382,310,336,316,t,25
5766086,2017-09-30,2817,송파,승차,71,114,145,265,280,209,...,354,407,374,357,162,151,96,87,t,0
5766087,2017-09-30,2817,송파,하차,65,388,141,224,231,177,...,213,271,238,259,229,139,196,151,t,12
5766088,2017-09-30,2818,가락시장(8),승차,84,129,190,279,366,449,...,564,479,474,446,322,273,295,252,t,1
5766089,2017-09-30,2818,가락시장(8),하차,97,228,255,483,513,445,...,477,463,470,541,379,239,258,193,t,152
5766090,2017-09-30,2819,문정,승차,52,134,226,331,493,346,...,489,540,697,788,249,218,208,233,t,1
5766091,2017-09-30,2819,문정,하차,74,637,433,397,420,340,...,357,286,339,361,412,243,286,302,t,0
5766092,2017-09-30,2820,장지,승차,147,326,422,761,813,704,...,963,976,1131,1177,909,671,675,828,t,0
5766093,2017-09-30,2820,장지,하차,46,239,384,772,866,635,...,910,854,1028,912,730,548,563,781,t,1
5766094,2017-09-30,2821,복정(8),승차,108,211,338,583,570,505,...,570,552,710,747,408,237,217,148,t,1
5766095,2017-09-30,2821,복정(8),하차,86,422,290,298,300,256,...,344,341,361,423,427,335,418,461,t,83
5766096,2017-09-30,2822,산성,승차,193,219,337,478,478,326,...,411,384,407,366,200,120,82,53,t,1
5766097,2017-09-30,2822,산성,하차,24,80,95,183,304,288,...,284,276,361,382,348,305,358,438,t,53
5766098,2017-09-30,2823,남한산성입구,승차,309,511,792,1066,1111,838,...,745,727,728,696,299,187,138,115,t,2
5766099,2017-09-30,2823,남한산성입구,하차,35,160,225,310,332,428,...,539,491,569,713,712,687,720,957,t,118
5766100,2017-09-30,2824,단대오거리,승차,284,432,597,886,765,680,...,674,694,654,640,344,215,186,155,t,3
5766101,2017-09-30,2824,단대오거리,하차,55,128,187,274,288,278,...,515,469,556,611,727,580,671,801,t,97
5766102,2017-09-30,2825,신흥,승차,109,190,220,350,329,224,...,363,354,439,365,217,158,157,102,t,0
5766103,2017-09-30,2825,신흥,하차,24,69,72,150,166,170,...,337,401,349,456,374,269,322,265,t,40
5766104,2017-09-30,2826,수진,승차,110,137,248,393,333,268,...,324,312,358,350,173,133,91,73,t,1
5766105,2017-09-30,2826,수진,하차,20,111,59,133,166,186,...,315,278,280,290,277,190,266,212,t,38
5766106,2017-09-30,2827,모란(8),승차,74,91,106,185,197,210,...,306,293,278,330,189,119,123,113,t,0
5766107,2017-09-30,2827,모란(8),하차,16,90,95,143,175,177,...,183,232,257,224,182,155,160,151,t,19

In [33]:
del df2['variable']

In [34]:
df2=df2.rename(columns = {' 날짜 ':'date'})
df2=df2.rename(columns = {' 역번호 ':'number'})
df2=df2.rename(columns = {' 역명 ':'name'})
df2=df2.rename(columns = {' 구분 ':'di'})

In [35]:
df2

                  date  number            name    di     t
0          2008-01-01      150       서울역(150)    승차    379
1          2008-01-01      150       서울역(150)    하차    145
2          2008-01-01      151        시청(151)    승차    131
3          2008-01-01      151        시청(151)    하차     35
4          2008-01-01      152        종각(152)    승차   1287
5          2008-01-01      152        종각(152)    하차     74
6          2008-01-01      153      종로3가(153)    승차    484
7          2008-01-01      153      종로3가(153)    하차     28
8          2008-01-01      154      종로5가(154)    승차     89
9          2008-01-01      154      종로5가(154)    하차     14
10         2008-01-01      155       동대문(155)    승차    190
11         2008-01-01      155       동대문(155)    하차     23
12         2008-01-01      156       신설동(156)    승차     65
13         2008-01-01      156       신설동(156)    하차     15
14         2008-01-01      157       제기동(157)    승차    156
15         2008-01-01      157       제기동(157)    하차     16
16         2008-01-01      158   청량리(지하)(158)    승차    230
17         2008-01-01      158   청량리(지하)(158)    하차     56
18         2008-01-01      159       동묘앞(159)    승차     27
19         2008-01-01      159       동묘앞(159)    하차      3
20         2008-01-01      201        시청(201)    승차     55
21         2008-01-01      201        시청(201)    하차     29
22         2008-01-01      202     을지로입구(202)    승차    163
23         2008-01-01      202     을지로입구(202)    하차     31
24         2008-01-01      203     을지로3가(203)    승차     23
25         2008-01-01      203     을지로3가(203)    하차     12
26         2008-01-01      204     을지로4가(204)    승차     11
27         2008-01-01      204     을지로4가(204)    하차      8
28         2008-01-01      205    동대문운동장(205)    승차    174
29         2008-01-01      205    동대문운동장(205)    하차     24
...                ...     ...             ...   ...   ...
38440690    2017-09-30    2813            강동구청    승차    14
38440691    2017-09-30    2813            강동구청    하차   148
38440692    2017-09-30    2814            몽촌토성    승차     0
38440693    2017-09-30    2814            몽촌토성    하차    17
38440694    2017-09-30    2815           잠실(8)    승차     1
38440695    2017-09-30    2815           잠실(8)    하차    44
38440696    2017-09-30    2816              석촌    승차     1
38440697    2017-09-30    2816              석촌    하차    25
38440698    2017-09-30    2817              송파    승차     0
38440699    2017-09-30    2817              송파    하차    12
38440700    2017-09-30    2818         가락시장(8)    승차     1
38440701    2017-09-30    2818         가락시장(8)    하차   152
38440702    2017-09-30    2819              문정    승차     1
38440703    2017-09-30    2819              문정    하차     0
38440704    2017-09-30    2820              장지    승차     0
38440705    2017-09-30    2820              장지    하차     1
38440706    2017-09-30    2821           복정(8)    승차     1
38440707    2017-09-30    2821           복정(8)    하차    83
38440708    2017-09-30    2822              산성    승차     1
38440709    2017-09-30    2822              산성    하차    53
38440710    2017-09-30    2823          남한산성입구    승차     2
38440711    2017-09-30    2823          남한산성입구    하차   118
38440712    2017-09-30    2824           단대오거리    승차     3
38440713    2017-09-30    2824           단대오거리    하차    97
38440714    2017-09-30    2825              신흥    승차     0
38440715    2017-09-30    2825              신흥    하차    40
38440716    2017-09-30    2826              수진    승차     1
38440717    2017-09-30    2826              수진    하차    38
38440718    2017-09-30    2827           모란(8)    승차     0
38440719    2017-09-30    2827           모란(8)    하차    19

[38440720 rows x 5 columns]

In [41]:
df3 = df2.copy()
df3['t'] = df3.t - df3.t.shift(-1)
df3.drop_duplicates(['date','number','name'])
df3

                  date  number            name    di       t
0          2008-01-01      150       서울역(150)    승차    234.0
1          2008-01-01      150       서울역(150)    하차     14.0
2          2008-01-01      151        시청(151)    승차     96.0
3          2008-01-01      151        시청(151)    하차  -1252.0
4          2008-01-01      152        종각(152)    승차   1213.0
5          2008-01-01      152        종각(152)    하차   -410.0
6          2008-01-01      153      종로3가(153)    승차    456.0
7          2008-01-01      153      종로3가(153)    하차    -61.0
8          2008-01-01      154      종로5가(154)    승차     75.0
9          2008-01-01      154      종로5가(154)    하차   -176.0
10         2008-01-01      155       동대문(155)    승차    167.0
11         2008-01-01      155       동대문(155)    하차    -42.0
12         2008-01-01      156       신설동(156)    승차     50.0
13         2008-01-01      156       신설동(156)    하차   -141.0
14         2008-01-01      157       제기동(157)    승차    140.0
15         2008-01-01      157       제기동(157)    하차   -214.0
16         2008-01-01      158   청량리(지하)(158)    승차    174.0
17         2008-01-01      158   청량리(지하)(158)    하차     29.0
18         2008-01-01      159       동묘앞(159)    승차     24.0
19         2008-01-01      159       동묘앞(159)    하차    -52.0
20         2008-01-01      201        시청(201)    승차     26.0
21         2008-01-01      201        시청(201)    하차   -134.0
22         2008-01-01      202     을지로입구(202)    승차    132.0
23         2008-01-01      202     을지로입구(202)    하차      8.0
24         2008-01-01      203     을지로3가(203)    승차     11.0
25         2008-01-01      203     을지로3가(203)    하차      1.0
26         2008-01-01      204     을지로4가(204)    승차      3.0
27         2008-01-01      204     을지로4가(204)    하차   -166.0
28         2008-01-01      205    동대문운동장(205)    승차    150.0
29         2008-01-01      205    동대문운동장(205)    하차    -75.0
...                ...     ...             ...   ...     ...
38440690    2017-09-30    2813            강동구청    승차  -134.0
38440691    2017-09-30    2813            강동구청    하차   148.0
38440692    2017-09-30    2814            몽촌토성    승차   -17.0
38440693    2017-09-30    2814            몽촌토성    하차    16.0
38440694    2017-09-30    2815           잠실(8)    승차   -43.0
38440695    2017-09-30    2815           잠실(8)    하차    43.0
38440696    2017-09-30    2816              석촌    승차   -24.0
38440697    2017-09-30    2816              석촌    하차    25.0
38440698    2017-09-30    2817              송파    승차   -12.0
38440699    2017-09-30    2817              송파    하차    11.0
38440700    2017-09-30    2818         가락시장(8)    승차  -151.0
38440701    2017-09-30    2818         가락시장(8)    하차   151.0
38440702    2017-09-30    2819              문정    승차     1.0
38440703    2017-09-30    2819              문정    하차     0.0
38440704    2017-09-30    2820              장지    승차    -1.0
38440705    2017-09-30    2820              장지    하차     0.0
38440706    2017-09-30    2821           복정(8)    승차   -82.0
38440707    2017-09-30    2821           복정(8)    하차    82.0
38440708    2017-09-30    2822              산성    승차   -52.0
38440709    2017-09-30    2822              산성    하차    51.0
38440710    2017-09-30    2823          남한산성입구    승차  -116.0
38440711    2017-09-30    2823          남한산성입구    하차   115.0
38440712    2017-09-30    2824           단대오거리    승차   -94.0
38440713    2017-09-30    2824           단대오거리    하차    97.0
38440714    2017-09-30    2825              신흥    승차   -40.0
38440715    2017-09-30    2825              신흥    하차    39.0
38440716    2017-09-30    2826              수진    승차   -37.0
38440717    2017-09-30    2826              수진    하차    38.0
38440718    2017-09-30    2827           모란(8)    승차   -19.0
38440719    2017-09-30    2827           모란(8)    하차     NaN

[38440720 rows x 5 columns]

In [42]:
df3 = df3.iloc[::2]

In [43]:
df3

                  date  number            name    di       t
0          2008-01-01      150       서울역(150)    승차    234.0
2          2008-01-01      151        시청(151)    승차     96.0
4          2008-01-01      152        종각(152)    승차   1213.0
6          2008-01-01      153      종로3가(153)    승차    456.0
8          2008-01-01      154      종로5가(154)    승차     75.0
10         2008-01-01      155       동대문(155)    승차    167.0
12         2008-01-01      156       신설동(156)    승차     50.0
14         2008-01-01      157       제기동(157)    승차    140.0
16         2008-01-01      158   청량리(지하)(158)    승차    174.0
18         2008-01-01      159       동묘앞(159)    승차     24.0
20         2008-01-01      201        시청(201)    승차     26.0
22         2008-01-01      202     을지로입구(202)    승차    132.0
24         2008-01-01      203     을지로3가(203)    승차     11.0
26         2008-01-01      204     을지로4가(204)    승차      3.0
28         2008-01-01      205    동대문운동장(205)    승차    150.0
30         2008-01-01      206        신당(206)    승차     78.0
32         2008-01-01      207      상왕십리(207)    승차    107.0
34         2008-01-01      208       왕십리(208)    승차     71.0
36         2008-01-01      209       한양대(209)    승차     32.0
38         2008-01-01      210        뚝섬(210)    승차     78.0
40         2008-01-01      211        성수(211)    승차    109.0
42         2008-01-01      212      건대입구(212)    승차    647.0
44         2008-01-01      213        구의(213)    승차    109.0
46         2008-01-01      214        강변(214)    승차     76.0
48         2008-01-01      215        성내(215)    승차     11.0
50         2008-01-01      216        잠실(216)    승차    265.0
52         2008-01-01      217        신천(217)    승차    532.0
54         2008-01-01      218     종합운동장(218)    승차     32.0
56         2008-01-01      219        삼성(219)    승차    227.0
58         2008-01-01      220        선릉(220)    승차    182.0
...                ...     ...             ...   ...     ...
38440660    2017-09-30    2749              철산    승차   -41.0
38440662    2017-09-30    2750           광명사거리    승차   -50.0
38440664    2017-09-30    2751              천왕    승차   -58.0
38440666    2017-09-30    2752           온수(7)    승차  -246.0
38440668    2017-09-30    2753             까치울    승차     0.0
38440670    2017-09-30    2754         부천종합운동장    승차    -1.0
38440672    2017-09-30    2755              춘의    승차   -47.0
38440674    2017-09-30    2756             신중동    승차   -75.0
38440676    2017-09-30    2757            부천시청    승차   -59.0
38440678    2017-09-30    2758              상동    승차   -70.0
38440680    2017-09-30    2759           삼산체육관    승차   -42.0
38440682    2017-09-30    2760             굴포천    승차  -138.0
38440684    2017-09-30    2761         부평구청(7)    승차  -108.0
38440686    2017-09-30    2811              암사    승차  -106.0
38440688    2017-09-30    2812           천호(8)    승차  -156.0
38440690    2017-09-30    2813            강동구청    승차  -134.0
38440692    2017-09-30    2814            몽촌토성    승차   -17.0
38440694    2017-09-30    2815           잠실(8)    승차   -43.0
38440696    2017-09-30    2816              석촌    승차   -24.0
38440698    2017-09-30    2817              송파    승차   -12.0
38440700    2017-09-30    2818         가락시장(8)    승차  -151.0
38440702    2017-09-30    2819              문정    승차     1.0
38440704    2017-09-30    2820              장지    승차    -1.0
38440706    2017-09-30    2821           복정(8)    승차   -82.0
38440708    2017-09-30    2822              산성    승차   -52.0
38440710    2017-09-30    2823          남한산성입구    승차  -116.0
38440712    2017-09-30    2824           단대오거리    승차   -94.0
38440714    2017-09-30    2825              신흥    승차   -40.0
38440716    2017-09-30    2826              수진    승차   -37.0
38440718    2017-09-30    2827           모란(8)    승차   -19.0

[19220360 rows x 5 columns]

In [44]:
del df3['di']

In [46]:
df3.to_csv('gg.csv')

In [47]:
df = pd.read_csv('gg.csv')

In [48]:
df

          Unnamed: 0          date  number            name       t
0                  0   2008-01-01      150       서울역(150)    234.0
1                  2   2008-01-01      151        시청(151)     96.0
2                  4   2008-01-01      152        종각(152)   1213.0
3                  6   2008-01-01      153      종로3가(153)    456.0
4                  8   2008-01-01      154      종로5가(154)     75.0
5                 10   2008-01-01      155       동대문(155)    167.0
6                 12   2008-01-01      156       신설동(156)     50.0
7                 14   2008-01-01      157       제기동(157)    140.0
8                 16   2008-01-01      158   청량리(지하)(158)    174.0
9                 18   2008-01-01      159       동묘앞(159)     24.0
10                20   2008-01-01      201        시청(201)     26.0
11                22   2008-01-01      202     을지로입구(202)    132.0
12                24   2008-01-01      203     을지로3가(203)     11.0
13                26   2008-01-01      204     을지로4가(204)      3.0
14                28   2008-01-01      205    동대문운동장(205)    150.0
15                30   2008-01-01      206        신당(206)     78.0
16                32   2008-01-01      207      상왕십리(207)    107.0
17                34   2008-01-01      208       왕십리(208)     71.0
18                36   2008-01-01      209       한양대(209)     32.0
19                38   2008-01-01      210        뚝섬(210)     78.0
20                40   2008-01-01      211        성수(211)    109.0
21                42   2008-01-01      212      건대입구(212)    647.0
22                44   2008-01-01      213        구의(213)    109.0
23                46   2008-01-01      214        강변(214)     76.0
24                48   2008-01-01      215        성내(215)     11.0
25                50   2008-01-01      216        잠실(216)    265.0
26                52   2008-01-01      217        신천(217)    532.0
27                54   2008-01-01      218     종합운동장(218)     32.0
28                56   2008-01-01      219        삼성(219)    227.0
29                58   2008-01-01      220        선릉(220)    182.0
...              ...           ...     ...             ...     ...
19220330    38440660    2017-09-30    2749              철산   -41.0
19220331    38440662    2017-09-30    2750           광명사거리   -50.0
19220332    38440664    2017-09-30    2751              천왕   -58.0
19220333    38440666    2017-09-30    2752           온수(7)  -246.0
19220334    38440668    2017-09-30    2753             까치울     0.0
19220335    38440670    2017-09-30    2754         부천종합운동장    -1.0
19220336    38440672    2017-09-30    2755              춘의   -47.0
19220337    38440674    2017-09-30    2756             신중동   -75.0
19220338    38440676    2017-09-30    2757            부천시청   -59.0
19220339    38440678    2017-09-30    2758              상동   -70.0
19220340    38440680    2017-09-30    2759           삼산체육관   -42.0
19220341    38440682    2017-09-30    2760             굴포천  -138.0
19220342    38440684    2017-09-30    2761         부평구청(7)  -108.0
19220343    38440686    2017-09-30    2811              암사  -106.0
19220344    38440688    2017-09-30    2812           천호(8)  -156.0
19220345    38440690    2017-09-30    2813            강동구청  -134.0
19220346    38440692    2017-09-30    2814            몽촌토성   -17.0
19220347    38440694    2017-09-30    2815           잠실(8)   -43.0
19220348    38440696    2017-09-30    2816              석촌   -24.0
19220349    38440698    2017-09-30    2817              송파   -12.0
19220350    38440700    2017-09-30    2818         가락시장(8)  -151.0
19220351    38440702    2017-09-30    2819              문정     1.0
19220352    38440704    2017-09-30    2820              장지    -1.0
19220353    38440706    2017-09-30    2821           복정(8)   -82.0
19220354    38440708    2017-09-30    2822              산성   -52.0
19220355    38440710    2017-09-30    2823          남한산성입구  -116.0
19220356    38440712    2017-09-30    2824           단대오거리   -94.0
19220357    38440714    2017-09-30    2825              신흥   -40.0
19220358    38440716    2017-09-30    2826              수진   -37.0
19220359    38440718    2017-09-30    2827           모란(8)   -19.0

[19220360 rows x 5 columns]

In [8]:
df

,date,number,name,div,a,b,c,d,e,f,...,k,l,m,n,o,p,q,r,s,t
0,2008-01-01,150,서울역(150),승차,379,287,371,876,965,1389,...,2520,3078,3495,3055,2952,2726,3307,2584,1059,264
1,2008-01-01,150,서울역(150),하차,145,707,689,1037,1170,1376,...,1955,2304,2203,2128,1747,1593,1078,744,406,558
2,2008-01-01,151,시청(151),승차,131,131,101,152,191,202,...,892,900,1154,1706,1444,1267,928,531,233,974
3,2008-01-01,151,시청(151),하차,35,158,203,393,375,460,...,1157,1153,1303,1190,830,454,284,141,107,185
4,2008-01-01,152,종각(152),승차,1287,867,400,330,345,338,...,1867,2269,2777,2834,2646,2784,2920,2290,802,1559
5,2008-01-01,152,종각(152),하차,74,147,261,473,597,698,...,2161,2298,2360,1997,1217,799,461,271,134,210
6,2008-01-01,153,종로3가(153),승차,484,290,192,218,281,429,...,1652,2000,1768,1745,1556,1598,1487,1318,455,1499
7,2008-01-01,153,종로3가(153),하차,28,80,116,238,390,609,...,1991,1896,1543,1160,926,431,324,190,127,384
8,2008-01-01,154,종로5가(154),승차,89,77,86,115,122,192,...,553,647,596,421,335,237,154,134,47,140
9,2008-01-01,154,종로5가(154),하차,14,76,93,123,137,193,...,445,399,393,272,190,167,138,125,104,42
10,2008-01-01,155,동대문(155),승차,190,149,152,253,365,390,...,900,891,867,764,587,489,386,287,155,139
11,2008-01-01,155,동대문(155),하차,23,111,120,150,299,331,...,1061,987,891,757,578,451,500,426,231,221
12,2008-01-01,156,신설동(156),승차,65,107,113,183,244,248,...,448,407,432,389,290,250,235,143,49,19
13,2008-01-01,156,신설동(156),하차,15,98,81,112,166,202,...,324,347,394,397,321,297,332,279,186,89
14,2008-01-01,157,제기동(157),승차,156,129,115,193,279,385,...,860,921,759,557,382,280,193,124,47,62
15,2008-01-01,157,제기동(157),하차,16,84,84,175,256,384,...,747,561,434,373,333,268,247,236,148,85
16,2008-01-01,158,청량리(지하)(158),승차,230,292,351,588,779,1076,...,2097,2152,2141,2109,1951,1534,1374,1001,316,60
17,2008-01-01,158,청량리(지하)(158),하차,56,428,510,522,872,1059,...,1848,1698,1777,1410,1254,1147,1068,900,546,403
18,2008-01-01,159,동묘앞(159),승차,27,26,22,41,63,109,...,428,441,367,194,112,92,73,70,26,10
19,2008-01-01,159,동묘앞(159),하차,3,45,54,84,96,132,...,371,309,184,158,101,128,106,117,86,61
20,2008-01-01,201,시청(201),승차,55,93,67,126,139,97,...,471,577,734,956,782,695,513,287,135,570
21,2008-01-01,201,시청(201),하차,29,107,131,196,262,237,...,794,757,795,799,456,385,200,113,70,148
22,2008-01-01,202,을지로입구(202),승차,163,96,106,129,245,245,...,1150,1519,1720,1994,1820,1842,1816,1216,329,1188
23,2008-01-01,202,을지로입구(202),하차,31,176,278,565,547,813,...,1712,1621,1448,1080,521,335,206,112,48,219
24,2008-01-01,203,을지로3가(203),승차,23,55,36,69,79,384,...,238,218,299,252,250,194,148,117,59,107
25,2008-01-01,203,을지로3가(203),하차,12,81,79,251,428,470,...,240,203,204,189,105,87,60,48,30,34
26,2008-01-01,204,을지로4가(204),승차,11,34,23,56,81,62,...,147,159,185,133,100,76,84,50,9,22
27,2008-01-01,204,을지로4가(204),하차,8,45,34,85,60,77,...,137,95,86,78,75,48,52,37,24,32
28,2008-01-01,205,동대문운동장(205),승차,174,131,109,171,210,178,...,875,1054,1087,1040,844,708,572,407,247,151
29,2008-01-01,205,동대문운동장(205),하차,24,100,102,168,242,377,...,1010,973,895,729,636,448,380,298,232,151
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1922006,2017-09-30,2813,강동구청,승차,120,239,397,561,601,519,...,547,596,603,499,299,195,154,116,56,14
1922007,2017-09-30,2813,강동구청,하차,27,149,211,311,321,297,...,469,514,589,555,497,383,494,516,288,148
1922008,2017-09-30,2814,몽촌토성,승차,67,90,165,273,254,287,...,657,781,986,772,453,237,223,200,80,0
1922009,2017-09-30,2814,몽촌토성,하차,32,163,189,256,367,427,...,618,522,458,354,205,216,229,264,111,17
1922010,2017-09-30,2815,잠실(8),승차,73,92,131,179,238,269,...,942,1177,1160,1311,1182,1150,1142,905,344,1
1922011,2017-09-30,2815,잠실(8),하차,27,195,343,785,954,902,...,1319,1505,1104,1023,562,397,300,213,129,44
1922012,2017-09-30,2816,석촌,승차,146,150,290,421,492,410,...,462,557,467,412,286,232,257,149,87,1
1922013,2017-09-30,2816,석촌,하차,25,168,189,360,383,379,...,412,465,520,462,382,310,336,316,230,25
1922014,2017-09-30,2817,송파,승차,71,114,145,265,280,209,...,407,374,357,274,162,151,96,87,45,0
1922015,2017-09-30,2817,송파,하차,65,388,141,224,231,177,...,271,238,259,248,229,139,196,151,114,12
1922016,2017-09-30,2818,가락시장(8),승차,84,129,190,279,366,449,...,479,474,446,399,322,273,295,252,160,1
1922017,2017-09-30,2818,가락시장(8),하차,97,228,255,483,513,445,...,463,470,541,460,379,239,258,193,165,152
1922018,2017-09-30,2819,문정,승차,52,134,226,331,493,346,...,540,697,788,522,249,218,208,233,85,1
1922019,2017-09-30,2819,문정,하차,74,637,433,397,420,340,...,286,339,361,438,412,243,286,302,168,0
1922020,2017-09-30,2820,장지,승차,147,326,422,761,813,704,...,976,1131,1177,1236,909,671,675,828,175,0
1922021,2017-09-30,2820,장지,하차,46,239,384,772,866,635,...,854,1028,912,1116,730,548,563,781,501,1
1922022,2017-09-30,2821,복정(8),승차,108,211,338,583,570,505,...,552,710,747,498,408,237,217,148,74,1
1922023,2017-09-30,2821,복정(8),하차,86,422,290,298,300,256,...,341,361,423,439,427,335,418,461,331,83
1922024,2017-09-30,2822,산성,승차,193,219,337,478,478,326,...,384,407,366,246,200,120,82,53,37,1
1922025,2017-09-30,2822,산성,하차,24,80,95,183,304,288,...,276,361,382,417,348,305,358,438,238,53
1922026,2017-09-30,2823,남한산성입구,승차,309,511,792,1066,1111,838,...,727,728,696,504,299,187,138,115,55,2
1922027,2017-09-30,2823,남한산성입구,하차,35,160,225,310,332,428,...,491,569,713,783,712,687,720,957,646,118
1922028,2017-09-30,2824,단대오거리,승차,284,432,597,886,765,680,...,694,654,640,515,344,215,186,155,74,3
1922029,2017-09-30,2824,단대오거리,하차,55,128,187,274,288,278,...,469,556,611,803,727,580,671,801,606,97
1922030,2017-09-30,2825,신흥,승차,109,190,220,350,329,224,...,354,439,365,298,217,158,157,102,39,0
1922031,2017-09-30,2825,신흥,하차,24,69,72,150,166,170,...,401,349,456,401,374,269,322,265,203,40
1922032,2017-09-30,2826,수진,승차,110,137,248,393,333,268,...,312,358,350,290,173,133,91,73,38,1
1922033,2017-09-30,2826,수진,하차,20,111,59,133,166,186,...,278,280,290,315,277,190,266,212,184,38
1922034,2017-09-30,2827,모란(8),승차,74,91,106,185,197,210,...,293,278,330,260,189,119,123,113,55,0
1922035,2017-09-30,2827,모란(8),하차,16,90,95,143,175,177,...,232,257,224,305,182,155,160,151,112,19

In [22]:
letters = list("abcdefghijklmnopqrst")
df = pd.concat([df.iloc[:, 5:25]]).assign(t=df[letters[5:]].values[0])
df = df.reset_index(drop=True)
df

ValueError: Length of values does not match length of index

In [23]:
df.iloc[:, 5:25]

,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t
0,287,371,876,965,1389,1989,2375,2588,2885,2520,3078,3495,3055,2952,2726,3307,2584,1059,264
1,707,689,1037,1170,1376,1451,1743,1984,2077,1955,2304,2203,2128,1747,1593,1078,744,406,558
2,131,101,152,191,202,275,361,471,678,892,900,1154,1706,1444,1267,928,531,233,974
3,158,203,393,375,460,591,841,1116,1148,1157,1153,1303,1190,830,454,284,141,107,185
4,867,400,330,345,338,595,791,1182,1475,1867,2269,2777,2834,2646,2784,2920,2290,802,1559
5,147,261,473,597,698,1074,1719,1817,2089,2161,2298,2360,1997,1217,799,461,271,134,210
6,290,192,218,281,429,566,943,1238,1449,1652,2000,1768,1745,1556,1598,1487,1318,455,1499
7,80,116,238,390,609,1001,1680,2246,2387,1991,1896,1543,1160,926,431,324,190,127,384
8,77,86,115,122,192,253,315,414,452,553,647,596,421,335,237,154,134,47,140
9,76,93,123,137,193,310,409,544,551,445,399,393,272,190,167,138,125,104,42
10,149,152,253,365,390,467,541,670,727,900,891,867,764,587,489,386,287,155,139
11,111,120,150,299,331,566,893,1005,1054,1061,987,891,757,578,451,500,426,231,221
12,107,113,183,244,248,311,378,416,416,448,407,432,389,290,250,235,143,49,19
13,98,81,112,166,202,218,332,428,365,324,347,394,397,321,297,332,279,186,89
14,129,115,193,279,385,486,463,638,666,860,921,759,557,382,280,193,124,47,62
15,84,84,175,256,384,509,698,949,891,747,561,434,373,333,268,247,236,148,85
16,292,351,588,779,1076,1257,1548,1938,2006,2097,2152,2141,2109,1951,1534,1374,1001,316,60
17,428,510,522,872,1059,1214,1513,1832,2078,1848,1698,1777,1410,1254,1147,1068,900,546,403
18,26,22,41,63,109,136,192,283,299,428,441,367,194,112,92,73,70,26,10
19,45,54,84,96,132,172,284,386,454,371,309,184,158,101,128,106,117,86,61
20,93,67,126,139,97,252,289,301,439,471,577,734,956,782,695,513,287,135,570
21,107,131,196,262,237,343,475,555,756,794,757,795,799,456,385,200,113,70,148
22,96,106,129,245,245,339,408,759,921,1150,1519,1720,1994,1820,1842,1816,1216,329,1188
23,176,278,565,547,813,836,1066,1444,1580,1712,1621,1448,1080,521,335,206,112,48,219
24,55,36,69,79,384,138,224,515,230,238,218,299,252,250,194,148,117,59,107
25,81,79,251,428,470,493,194,225,236,240,203,204,189,105,87,60,48,30,34
26,34,23,56,81,62,116,123,125,162,147,159,185,133,100,76,84,50,9,22
27,45,34,85,60,77,110,124,154,138,137,95,86,78,75,48,52,37,24,32
28,131,109,171,210,178,233,381,458,707,875,1054,1087,1040,844,708,572,407,247,151
29,100,102,168,242,377,412,670,861,1114,1010,973,895,729,636,448,380,298,232,151
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1922006,239,397,561,601,519,510,545,587,556,547,596,603,499,299,195,154,116,56,14
1922007,149,211,311,321,297,355,491,475,489,469,514,589,555,497,383,494,516,288,148
1922008,90,165,273,254,287,297,395,468,457,657,781,986,772,453,237,223,200,80,0
1922009,163,189,256,367,427,508,640,794,802,618,522,458,354,205,216,229,264,111,17
1922010,92,131,179,238,269,392,484,580,803,942,1177,1160,1311,1182,1150,1142,905,344,1
1922011,195,343,785,954,902,1085,1298,1462,1307,1319,1505,1104,1023,562,397,300,213,129,44
1922012,150,290,421,492,410,403,494,519,446,462,557,467,412,286,232,257,149,87,1
1922013,168,189,360,383,379,363,409,463,457,412,465,520,462,382,310,336,316,230,25
1922014,114,145,265,280,209,261,358,343,354,407,374,357,274,162,151,96,87,45,0
1922015,388,141,224,231,177,218,215,246,213,271,238,259,248,229,139,196,151,114,12
1922016,129,190,279,366,449,454,500,503,564,479,474,446,399,322,273,295,252,160,1
1922017,228,255,483,513,445,450,441,457,477,463,470,541,460,379,239,258,193,165,152
1922018,134,226,331,493,346,383,442,504,489,540,697,788,522,249,218,208,233,85,1
1922019,637,433,397,420,340,338,383,343,357,286,339,361,438,412,243,286,302,168,0
1922020,326,422,761,813,704,744,860,847,963,976,1131,1177,1236,909,671,675,828,175,0
1922021,239,384,772,866,635,737,1037,934,910,854,1028,912,1116,730,548,563,781,501,1
1922022,211,338,583,570,505,532,489,563,570,552,710,747,498,408,237,217,148,74,1
1922023,422,290,298,300,256,250,292,343,344,341,361,423,439,427,335,418,461,331,83
1922024,219,337,478,478,326,339,413,412,411,384,407,366,246,200,120,82,53,37,1
1922025,80,95,183,304,288,244,252,245,284,276,361,382,417,348,305,358,438,238,53
1922026,511,792,1066,1111,838,780,911,805,745,727,728,696,504,299,187,138,115,55,2
1922027,160,225,310,332,428,401,465,452,539,491,569,713,783,712,687,720,957,646,118
1922028,432,597,886,765,680,723,759,715,674,694,654,640,515,344,215,186,155,74,3
1922029,128,187,274,288,278,324,421,401,515,469,556,611,803,727,580,671,801,606,97
1922030,190,220,350,329,224,268,320,299,363,354,439,365,298,217,158,157,102,39,0
1922031,69,72,150,166,170,231,277,372,337,401,349,456,401,374,269,322,265,203,40
1922032,137,248,393,333,268,324,337,374,324,312,358,350,290,173,133,91,73,38,1
1922033,111,59,133,166,186,221,253,317,315,278,280,290,315,277,190,266,212,184,38
1922034,91,106,185,197,210,295,363,349,306,293,278,330,260,189,119,123,113,55,0
1922035,90,95,143,175,177,196,185,174,183,232,257,224,305,182,155,160,151,112,19

In [24]:
s=pd.Series(df.columns)
s[(s>='a').cummax()==1]='a'
df.columns=s
df=df.melt()

yourdf=df.set_index(['variable',df.groupby('variable').cumcount()]).\
          value.unstack(0).ffill()
yourdf

variable             a
0          2008-01-01
1          2008-01-01
2          2008-01-01
3          2008-01-01
4          2008-01-01
5          2008-01-01
6          2008-01-01
7          2008-01-01
8          2008-01-01
9          2008-01-01
10         2008-01-01
11         2008-01-01
12         2008-01-01
13         2008-01-01
14         2008-01-01
15         2008-01-01
16         2008-01-01
17         2008-01-01
18         2008-01-01
19         2008-01-01
20         2008-01-01
21         2008-01-01
22         2008-01-01
23         2008-01-01
24         2008-01-01
25         2008-01-01
26         2008-01-01
27         2008-01-01
28         2008-01-01
29         2008-01-01
...                ...
46128834            14
46128835           148
46128836             0
46128837            17
46128838             1
46128839            44
46128840             1
46128841            25
46128842             0
46128843            12
46128844             1
46128845           152
46128846             1
46128847             0
46128848             0
46128849             1
46128850             1
46128851            83
46128852             1
46128853            53
46128854             2
46128855           118
46128856             3
46128857            97
46128858             0
46128859            40
46128860             1
46128861            38
46128862             0
46128863            19

[46128864 rows x 1 columns]

In [27]:
df

,date,number,name,div,a,b,c,d,e,f,...,k,l,m,n,o,p,q,r,s,t
0,2008-01-01,150,서울역(150),승차,379,287,371,876,965,1389,...,2520,3078,3495,3055,2952,2726,3307,2584,1059,264
1,2008-01-01,150,서울역(150),하차,145,707,689,1037,1170,1376,...,1955,2304,2203,2128,1747,1593,1078,744,406,558
2,2008-01-01,151,시청(151),승차,131,131,101,152,191,202,...,892,900,1154,1706,1444,1267,928,531,233,974
3,2008-01-01,151,시청(151),하차,35,158,203,393,375,460,...,1157,1153,1303,1190,830,454,284,141,107,185
4,2008-01-01,152,종각(152),승차,1287,867,400,330,345,338,...,1867,2269,2777,2834,2646,2784,2920,2290,802,1559
5,2008-01-01,152,종각(152),하차,74,147,261,473,597,698,...,2161,2298,2360,1997,1217,799,461,271,134,210
6,2008-01-01,153,종로3가(153),승차,484,290,192,218,281,429,...,1652,2000,1768,1745,1556,1598,1487,1318,455,1499
7,2008-01-01,153,종로3가(153),하차,28,80,116,238,390,609,...,1991,1896,1543,1160,926,431,324,190,127,384
8,2008-01-01,154,종로5가(154),승차,89,77,86,115,122,192,...,553,647,596,421,335,237,154,134,47,140
9,2008-01-01,154,종로5가(154),하차,14,76,93,123,137,193,...,445,399,393,272,190,167,138,125,104,42
10,2008-01-01,155,동대문(155),승차,190,149,152,253,365,390,...,900,891,867,764,587,489,386,287,155,139
11,2008-01-01,155,동대문(155),하차,23,111,120,150,299,331,...,1061,987,891,757,578,451,500,426,231,221
12,2008-01-01,156,신설동(156),승차,65,107,113,183,244,248,...,448,407,432,389,290,250,235,143,49,19
13,2008-01-01,156,신설동(156),하차,15,98,81,112,166,202,...,324,347,394,397,321,297,332,279,186,89
14,2008-01-01,157,제기동(157),승차,156,129,115,193,279,385,...,860,921,759,557,382,280,193,124,47,62
15,2008-01-01,157,제기동(157),하차,16,84,84,175,256,384,...,747,561,434,373,333,268,247,236,148,85
16,2008-01-01,158,청량리(지하)(158),승차,230,292,351,588,779,1076,...,2097,2152,2141,2109,1951,1534,1374,1001,316,60
17,2008-01-01,158,청량리(지하)(158),하차,56,428,510,522,872,1059,...,1848,1698,1777,1410,1254,1147,1068,900,546,403
18,2008-01-01,159,동묘앞(159),승차,27,26,22,41,63,109,...,428,441,367,194,112,92,73,70,26,10
19,2008-01-01,159,동묘앞(159),하차,3,45,54,84,96,132,...,371,309,184,158,101,128,106,117,86,61
20,2008-01-01,201,시청(201),승차,55,93,67,126,139,97,...,471,577,734,956,782,695,513,287,135,570
21,2008-01-01,201,시청(201),하차,29,107,131,196,262,237,...,794,757,795,799,456,385,200,113,70,148
22,2008-01-01,202,을지로입구(202),승차,163,96,106,129,245,245,...,1150,1519,1720,1994,1820,1842,1816,1216,329,1188
23,2008-01-01,202,을지로입구(202),하차,31,176,278,565,547,813,...,1712,1621,1448,1080,521,335,206,112,48,219
24,2008-01-01,203,을지로3가(203),승차,23,55,36,69,79,384,...,238,218,299,252,250,194,148,117,59,107
25,2008-01-01,203,을지로3가(203),하차,12,81,79,251,428,470,...,240,203,204,189,105,87,60,48,30,34
26,2008-01-01,204,을지로4가(204),승차,11,34,23,56,81,62,...,147,159,185,133,100,76,84,50,9,22
27,2008-01-01,204,을지로4가(204),하차,8,45,34,85,60,77,...,137,95,86,78,75,48,52,37,24,32
28,2008-01-01,205,동대문운동장(205),승차,174,131,109,171,210,178,...,875,1054,1087,1040,844,708,572,407,247,151
29,2008-01-01,205,동대문운동장(205),하차,24,100,102,168,242,377,...,1010,973,895,729,636,448,380,298,232,151
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1922006,2017-09-30,2813,강동구청,승차,120,239,397,561,601,519,...,547,596,603,499,299,195,154,116,56,14
1922007,2017-09-30,2813,강동구청,하차,27,149,211,311,321,297,...,469,514,589,555,497,383,494,516,288,148
1922008,2017-09-30,2814,몽촌토성,승차,67,90,165,273,254,287,...,657,781,986,772,453,237,223,200,80,0
1922009,2017-09-30,2814,몽촌토성,하차,32,163,189,256,367,427,...,618,522,458,354,205,216,229,264,111,17
1922010,2017-09-30,2815,잠실(8),승차,73,92,131,179,238,269,...,942,1177,1160,1311,1182,1150,1142,905,344,1
1922011,2017-09-30,2815,잠실(8),하차,27,195,343,785,954,902,...,1319,1505,1104,1023,562,397,300,213,129,44
1922012,2017-09-30,2816,석촌,승차,146,150,290,421,492,410,...,462,557,467,412,286,232,257,149,87,1
1922013,2017-09-30,2816,석촌,하차,25,168,189,360,383,379,...,412,465,520,462,382,310,336,316,230,25
1922014,2017-09-30,2817,송파,승차,71,114,145,265,280,209,...,407,374,357,274,162,151,96,87,45,0
1922015,2017-09-30,2817,송파,하차,65,388,141,224,231,177,...,271,238,259,248,229,139,196,151,114,12
1922016,2017-09-30,2818,가락시장(8),승차,84,129,190,279,366,449,...,479,474,446,399,322,273,295,252,160,1
1922017,2017-09-30,2818,가락시장(8),하차,97,228,255,483,513,445,...,463,470,541,460,379,239,258,193,165,152
1922018,2017-09-30,2819,문정,승차,52,134,226,331,493,346,...,540,697,788,522,249,218,208,233,85,1
1922019,2017-09-30,2819,문정,하차,74,637,433,397,420,340,...,286,339,361,438,412,243,286,302,168,0
1922020,2017-09-30,2820,장지,승차,147,326,422,761,813,704,...,976,1131,1177,1236,909,671,675,828,175,0
1922021,2017-09-30,2820,장지,하차,46,239,384,772,866,635,...,854,1028,912,1116,730,548,563,781,501,1
1922022,2017-09-30,2821,복정(8),승차,108,211,338,583,570,505,...,552,710,747,498,408,237,217,148,74,1
1922023,2017-09-30,2821,복정(8),하차,86,422,290,298,300,256,...,341,361,423,439,427,335,418,461,331,83
1922024,2017-09-30,2822,산성,승차,193,219,337,478,478,326,...,384,407,366,246,200,120,82,53,37,1
1922025,2017-09-30,2822,산성,하차,24,80,95,183,304,288,...,276,361,382,417,348,305,358,438,238,53
1922026,2017-09-30,2823,남한산성입구,승차,309,511,792,1066,1111,838,...,727,728,696,504,299,187,138,115,55,2
1922027,2017-09-30,2823,남한산성입구,하차,35,160,225,310,332,428,...,491,569,713,783,712,687,720,957,646,118
1922028,2017-09-30,2824,단대오거리,승차,284,432,597,886,765,680,...,694,654,640,515,344,215,186,155,74,3
1922029,2017-09-30,2824,단대오거리,하차,55,128,187,274,288,278,...,469,556,611,803,727,580,671,801,606,97
1922030,2017-09-30,2825,신흥,승차,109,190,220,350,329,224,...,354,439,365,298,217,158,157,102,39,0
1922031,2017-09-30,2825,신흥,하차,24,69,72,150,166,170,...,401,349,456,401,374,269,322,265,203,40
1922032,2017-09-30,2826,수진,승차,110,137,248,393,333,268,...,312,358,350,290,173,133,91,73,38,1
1922033,2017-09-30,2826,수진,하차,20,111,59,133,166,186,...,278,280,290,315,277,190,266,212,184,38
1922034,2017-09-30,2827,모란(8),승차,74,91,106,185,197,210,...,293,278,330,260,189,119,123,113,55,0
1922035,2017-09-30,2827,모란(8),하차,16,90,95,143,175,177,...,232,257,224,305,182,155,160,151,112,19

In [35]:
df1 = df.iloc[:,4:25]
df1 = df1.append([df1]*(len(df.iloc[:,4:25].T)-1))
df1.insert(df1.shape[1]+5,'a',list(df.iloc[:,4:25].values[0]))
df1

MemoryError:

In [34]:
df1.shape[1]

20